### ISSUE TITLE
concurrent map writes if more than one client used in the same time.

### ISSUE THREAD

**Issue by zwpaper** [aliyun/alibaba-cloud-sdk-go#257]
* **Product and API**:
ECS 
`client.DescribeInstanceAttribute`

* **Platform**:
macOS 10.14
Golang 1.11

* **How to Reproduce**
create more than one client in the same time, and use in two goroutines:

```
client1, err := ecs.NewClientWithAccessKey(config.RegionID, config.AccessKey, config.AccessSecret)
client2, err := ecs.NewClientWithAccessKey(config.RegionID, config.AccessKey, config.AccessSecret)
```

Trace Stack:
personal file deleted

```
fatal error: concurrent map writes

goroutine 10 [running]:
runtime.throw(0x18b46ee, 0x15)
	/usr/local/opt/go/libexec/src/runtime/panic.go:608 +0x72 fp=0xc0001e8aa8 sp=0xc0001e8a78 pc=0x102c0a2
runtime.mapassign_faststr(0x17487c0, 0xc0001532f0, 0x18af0cf, 0x6, 0x18af4a8)
	/usr/local/opt/go/libexec/src/runtime/map_faststr.go:199 +0x3da fp=0xc0001e8b10 sp=0xc0001e8aa8 pc=0x1013d4a
github.com/aliyun/alibaba-cloud-sdk-go/sdk.initLogMsg()
	/Users/user/code/golang/src/github.com/aliyun/alibaba-cloud-sdk-go/sdk/logger.go:28 +0x83 fp=0xc0001e8b60 sp=0xc0001e8b10 pc=0x1378753
github.com/aliyun/alibaba-cloud-sdk-go/sdk.(*Client).DoActionWithSigner(0xc0000b5040, 0x1957620, 0xc0001ca1e0, 0x1945700, 0xc0001de280, 0x0, 0x0, 0x0, 0x0)
	/Users/user/code/golang/src/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go:459 +0x7c fp=0xc0001e8e18 sp=0xc0001e8b60 pc=0x1375fdc
github.com/aliyun/alibaba-cloud-sdk-go/sdk.(*Client).DoAction(0xc0000b5040, 0x1957620, 0xc0001ca1e0, 0x1945700, 0xc0001de280, 0xc0001d4150, 0xc0001cc018)
	/Users/user/code/golang/src/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go:300 +0x5b fp=0xc0001e8e70 sp=0xc0001e8e18 pc=0x1374bfb
github.com/aliyun/alibaba-cloud-sdk-go/services/ecs.(*Client).DescribeInstanceAttribute(0xc0000b5040, 0xc0001ca1e0, 0x0, 0x0, 0xc000052710)
runtime.goexit()
	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0001e8f90 sp=0xc0001e8f88 pc=0x1058b61
created by main.initInstances

```

Caused by:
```
var fieldMap = make(map[string]string)

func (client *Client) printLog(err error) {
	if err != nil {
		fieldMap["{error}"] = err.Error()
	}
	fieldMap["{time}"] = time.Now().Format("2006-01-02 15:04:05")
	fieldMap["{ts}"] = utils.GetTimeInFormatISO8601()
	fieldMap["{channel}"] = logChannel
...
```

`fieldMap` defined as a global var, and used in struct method.

**Comment by wenzuochao** [comment]
I'm sorry for the fault,  I have put a request to fix it.  Thanks for your support to our project. #258

**Comment by wenzuochao** [comment]
> I'm sorry for the fault, I have put a request to fix it. Thanks for your support to our project. #258

I have merged the pull request.  Please update your codes and try again. If you still meet troubles about it, please tell us.
