### ISSUE TITLE
alpine 作为基镜像,sdk挂了

### ISSUE THREAD

**Issue by wuxingzhong** [aliyun/alibaba-cloud-sdk-go#350]
* **问题描述**:
使用sdk时在开发机器或者centos作为基础镜像sdk正常运行, 当将基础镜像换成alpine时,sdk必挂

* **产品和接口**:
发送短信接口 SendSms

* **平台**:
docker,  alpine:3.10 作为基镜像

* **最小代码**:
编译命令:
```bash
export LDFLAGS="-ldflags '-s'" 
CGO_ENABLED=0  go install -a -gcflags='-N -l' ${LDFLAGS} -mod=vendor  -v ./cmd/...
```
```go
	request := dysmsapi.CreateSendSmsRequest()
	request.Scheme = "https"

	request.PhoneNumbers = mobile
	request.SignName = c.conf.Template[templateIndex].SignName
	request.TemplateCode = c.conf.Template[templateIndex].TemplateCode
	request.TemplateParam = templateParam

	log.Info("request--->:%#v", request)
	log.Info("c.client--->:%#v", c.client)
	response, err = c.client.SendSms(request)
	if err != nil {
		log.Error("%v", err)
	}
```
* **错误信息**:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xad7bee]

goroutine 25 [running]:
github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses.(*BaseResponse).parseFromHttpResponse(0xc00026bdc0, 0x0, 0x0, 0x0)
        /go/src/app/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses/response.go:106 +0x2e
github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses.Unmarshal(0xe691c0, 0xc00000e948, 0x0, 0xd22068, 0x4, 0x14caa60, 0x4b5e795)
        /go/src/app/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses/response.go:40 +0x45
github.com/aliyun/alibaba-cloud-sdk-go/sdk.(*Client).DoActionWithSigner(0xc0003a62a0, 0xe76f20, 0xc000275f80, 0xe691c0, 0xc00000e948, 0x0, 0x0, 0xe4d740, 0xc   00044da10)
        /go/src/app/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go:610 +0xf51
github.com/aliyun/alibaba-cloud-sdk-go/sdk.(*Client).DoAction(...)
        /go/src/app/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go:308
github.com/aliyun/alibaba-cloud-sdk-go/sdk.(*Client).ProcessCommonRequest(0xc0003a62a0, 0xc000275f80, 0x40cf1d, 0xcd8e40, 0xc00046a7e0)
        /go/src/app/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go:758 +0xae
github.com/aliyun/alibaba-cloud-sdk-go/sdk/endpoints.(*LocationResolver).TryResolve(0x14e77c0, 0xc000416d80, 0x3, 0xc000418db0, 0x10, 0x10, 0xc529e0)
        /go/src/app/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/endpoints/location_resolver.go:97 +0x5bb
github.com/aliyun/alibaba-cloud-sdk-go/sdk/endpoints.Resolve(0xc000416d80, 0xc000418db0, 0x7, 0x8, 0x0)
        /go/src/app/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/endpoints/resolver.go:52 +0xae
github.com/aliyun/alibaba-cloud-sdk-go/sdk.(*Client).buildRequestWithSigner(0xc0003a62a0, 0xe77f60, 0xc00025b540, 0x0, 0x0, 0xd2204c, 0x4, 0x0)
        /go/src/app/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go:372 +0x718
github.com/aliyun/alibaba-cloud-sdk-go/sdk.(*Client).DoActionWithSigner(0xc0003a62a0, 0xe77f60, 0xc00025b540, 0xe695e0, 0xc0000e7db0, 0x0, 0x0, 0x0, 0x0)
        /go/src/app/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go:512 +0x130
github.com/aliyun/alibaba-cloud-sdk-go/sdk.(*Client).DoAction(...)
        /go/src/app/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go:308
github.com/aliyun/alibaba-cloud-sdk-go/services/dysmsapi.(*Client).SendSms(0xc0003a62a0, 0xc00025b540, 0xc0000dbec0, 0x1, 0x1)
        /go/src/app/vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/dysmsapi/send_sms.go:27 +0xa2
campus/ucs-sms/internal/dao/sms.(*Client).SendSms(0xc0003a17a0, 0xc00014420c, 0xb, 0x0, 0xc000458220, 0x12, 0x0, 0x0, 0x0)
        /go/src/app/ucs-sms/internal/dao/sms/sms.go:54 +0x33e
campus/ucs-sms/internal/dao.(*dao).SendVcode(0xc00000e5f8, 0xc00014420c, 0xb, 0x0, 0xc00014421e, 0x6, 0x0, 0x0)
```

**Comment by wuxingzhong** [comment]
dockerfile 信息
```
#build stage
FROM golang:1.12 AS builder
ARG GO111MODULE=on
ARG GOPROXY=https://goproxy.cn
ARG LDFLAGS=""

COPY . .

RUN CGO_ENABLED=0  go install -a -gcflags='-N -l' ${LDFLAGS} -mod=vendor  -v ./cmd/...

#final stage 
FROM base-alpine:3.10
......
```

**Comment by wenzuochao** [comment]
> dockerfile 信息
> 
> ```
> #build stage
> FROM golang:1.12 AS builder
> ARG GO111MODULE=on
> ARG GOPROXY=https://goproxy.cn
> ARG LDFLAGS=""
> 
> COPY . .
> 
> RUN CGO_ENABLED=0  go install -a -gcflags='-N -l' ${LDFLAGS} -mod=vendor  -v ./cmd/...
> 
> #final stage 
> FROM alpine:3.10
> ......
> ```
很抱歉对您造成困扰，能麻烦您给一下服务端的真实返回的 body 吗？问题应该在于返回的 body 与定义的response不一致导致，所以我这边需要比对一下

**Comment by wuxingzhong** [comment]
> > dockerfile 信息
> > ```
> > #build stage
> > FROM golang:1.12 AS builder
> > ARG GO111MODULE=on
> > ARG GOPROXY=https://goproxy.cn
> > ARG LDFLAGS=""
> > 
> > COPY . .
> > 
> > RUN CGO_ENABLED=0  go install -a -gcflags='-N -l' ${LDFLAGS} -mod=vendor  -v ./cmd/...
> > 
> > #final stage 
> > FROM alpine:3.10
> > ......
> > ```
> 
> 很抱歉对您造成困扰，能麻烦您给一下服务端的真实返回的 body 吗？问题应该在于返回的 body 与定义的response不一致导致，所以我这边需要比对一下

**Comment by wuxingzhong** [comment]
FROM alpine:3.10
改成 
FROM centos:7
就没有这样问题了, 所以是系统导致返回body不同么?

**Comment by wenzuochao** [comment]
> FROM alpine:3.10
> 改成
> FROM centos:7
> 就没有这样问题了, 所以是系统导致返回body不同么?

能看一下您在 alpine:3.10 环境下的调用返回吗？我这边看了一下，异常的位置在 body.Close(),会不会是body为空引起的空指针呢

**Comment by wuxingzhong** [comment]
![image](https://user-images.githubusercontent.com/7947984/68173382-befe2180-ffb5-11e9-8c88-afe3f4f4c5a6.png)

**Comment by wenzuochao** [comment]
你可以添加一下环境变量 DEBUG=sdk，可以打印出请求过程，例如请求的url，header，以及返回的header，

**Comment by wuxingzhong** [comment]
应该是alpine没安装ca-certificate导致的

**Comment by wuxingzhong** [comment]
```
 Error: Get https://location-readonly.aliyuncs.com/?AccessKeyId=LTAIVqxlpOjGY4xt&Action=DescribeEndpoints&Format=JSON&Id=cn-hangzhou&RegionId=cn-hangzhou&ServiceCode=dysmsapi&Signature=rUqSX6oi4cC75NTctyEq%2BfykZ1k%3D&SignatureMethod=HMAC-SHA1&SignatureNonce=60540e56c466287a820f871c7fb6e1c6&SignatureType=&SignatureVersion=1.0&Timestamp=2019-11-05T02%3A24%3A21Z&Type=openAPI&Version=2015-06-12: x509: certificate signed by unknown authority.
 ```

我加下配置试试

**Comment by wenzuochao** [comment]
也就是说，你之前的请求没跑成功，这边也有 sdk 的问题，对此我感到非常抱歉，我这边修复一下问题

**Comment by wuxingzhong** [comment]
加了ca-certificates, 可以了, 不过sdk也要加固下
```
FROM alpine:3.10 
RUN apk add --no-cache ca-certificates
```

**Comment by wenzuochao** [comment]
> 加了ca-certificates, 可以了, 不过sdk也要加固下
> 
> ```
> FROM alpine:3.10 
> RUN apk add --no-cache ca-certificates
> ```

是的，请求错误不应该去读取 body 的，这个是我们这边的问题，我这边修复了会通知您的

**Comment by wenzuochao** [comment]
已经将修复 pr #351 合入了，你可以在项目中拉取最新的代码，如果没问题的话，麻烦您关闭 issue。
