### ISSUE TITLE
SIGSEGV when calling Container Service's DescribeClusterDetail

### ISSUE THREAD

**Issue by bonifaido** [aliyun/alibaba-cloud-sdk-go#82]
This happens sporadically when calling DescribeClusterDetail during cluster creation:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x246280e]

goroutine 1071 [running]:
github.com/banzaicloud/pipeline/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses.(*BaseResponse).parseFromHttpResponse(0xc4200db000, 0x0, 0x0, 0x0)
	/Users/nandi/go/src/github.com/banzaicloud/pipeline/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses/response.go:99 +0x2e
github.com/banzaicloud/pipeline/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses.Unmarshal(0x3d2a520, 0xc4202332e8, 0x0, 0x3a66ba6, 0x4, 0xa, 0xc420b46900)
	/Users/nandi/go/src/github.com/banzaicloud/pipeline/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses/response.go:38 +0x45
github.com/banzaicloud/pipeline/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk.(*Client).DoActionWithSigner(0xc420fa2410, 0x3d4dca0, 0xc420ece8c0, 0x3d2a520, 0xc4202332e8, 0x0, 0x0, 0x2475501, 0xc4200db000)
	/Users/nandi/go/src/github.com/banzaicloud/pipeline/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go:274 +0x59e
github.com/banzaicloud/pipeline/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk.(*Client).DoAction(0xc420fa2410, 0x3d4dca0, 0xc420ece8c0, 0x3d2a520, 0xc4202332e8, 0xc420b46800, 0x3a7cd3d)
	/Users/nandi/go/src/github.com/banzaicloud/pipeline/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go:151 +0x5b
github.com/banzaicloud/pipeline/vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cs.(*Client).DescribeClusterDetail(0xc420fa2410, 0xc420ece8c0, 0x1e13, 0x2, 0x7fffffe00000)
	/Users/nandi/go/src/github.com/banzaicloud/pipeline/vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/cs/describe_cluster_detail.go:27 +0x99
```

**Comment by xiaozhu36** [comment]
HI @bonifaido Did you set `client.config.AutoRetry` as "false" to close auto-retry?

**Comment by bonifaido** [comment]
Hi @xiaozhu36, yes it was set to false in this case, might be causing the issue you mean?

**Comment by jxyowen** [comment]
Hi @bonifaido ,I have fixed this bug,and you can update with master branch, or use tag version 1.25.9

**Comment by bonifaido** [comment]
@jxyowen great, thank you! I will update to 1.25.9 and test it.

**Comment by bonifaido** [comment]
Seems to be working! Thank you @jxyowen
