### ISSUE TITLE
README demo代码运行 panic

### ISSUE THREAD

**Issue by jokimina** [aliyun/alibaba-cloud-sdk-go#92]
```
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/aliyun/alibaba-cloud-sdk-go/sdk/endpoints.(*LocationResolver).TryResolve(0x140c7e8, 0xc000056180, 0x0, 0x0, 0x1a0000, 0x0, 0x0)
	C:/Users/xiaodong/go/src/github.com/aliyun/alibaba-cloud-sdk-go/sdk/endpoints/location_resolver.go:59 +0xc0f
github.com/aliyun/alibaba-cloud-sdk-go/sdk/endpoints.Resolve(0xc000056180, 0xc000053320, 0x7, 0x12, 0xc0000db2b8)
	C:/Users/xiaodong/go/src/github.com/aliyun/alibaba-cloud-sdk-go/sdk/endpoints/resolver.go:40 +0x89
github.com/aliyun/alibaba-cloud-sdk-go/sdk.(*Client).DoActionWithSigner(0xc00009c1e0, 0xbe54c0, 0xc000028840, 0xbd6f20, 0xc00009c230, 0x0, 0x0, 0xa28d01, 0xc000054580)
	C:/Users/xiaodong/go/src/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go:217 +0x2ea
github.com/aliyun/alibaba-cloud-sdk-go/sdk.(*Client).DoAction(0xc00009c1e0, 0xbe54c0, 0xc000028840, 0xbd6f20, 0xc00009c230, 0xa, 0xb7890c)
	C:/Users/xiaodong/go/src/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go:151 +0x62
github.com/aliyun/alibaba-cloud-sdk-go/services/ecs.(*Client).DescribeInstances(0xc00009c1e0, 0xc000028840, 0x2, 0x10, 0xb6dd9f)
	C:/Users/xiaodong/go/src/github.com/aliyun/alibaba-cloud-sdk-go/services/ecs/describe_instances.go:27 +0x9f
```

**Comment by JacksonTian** [comment]
请更新下代码，我们已经做了fix。
